---
driver:
  name: vagrant
  customize:
    memory: 5000
    ioapic: 'on'
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

  network:
  #- ["forwarded_port", {guest: 8080, host: 9991}]

provisioner:
  name: chef_solo
#  require_chef_omnibus: 12.4.3


platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-16.04
#  - name: centos-7.2

suites: 
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[kzookeeper::install]
      - recipe[kkafka::install]
      - recipe[kzookeeper::default]
      - recipe[kkafka::default]
#      - recipe[kkafka::monitor]
    attributes:
         kagent:
            user: 'glassfish'
            group: 'glassfish'
            dir: '/srv/hops'
            enabled: 'false'
         kzookeeper:
            user: 'glassfish'
            group: 'glassfish'
            default:
               private_ips: ["10.0.2.15"]
            dir: "/srv/hops"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
         kkafka:
            user: 'glassfish'
            group: 'glassfish'
            dir: "/srv/hops"
            ulimit_file: 128000
            broker:
              log_dirs: ['/srv/hops/kafka-logs']
            default:
                private_ips: ["10.0.2.15"]
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]

